### ISSUE TITLE
Questions and suggestion

### ISSUE THREAD

**Issue by zgbkdlm** [probml/JSL#51]
Very nice work :+1:! I also had some implementations of filters and smoothers in https://github.com/spdes/chirpgp/blob/main/chirpgp/filters_smoothers.py, and I am wondering whether some of them can be integrated into this project if you need them. 

Can I ask what is the difference between JSL and ssm-jax?

BTW, there is a license problem with the matlab codes https://github.com/probml/JSL/tree/main/jsl/sarkka-matlab. These are using GPL licesne. Your current project definition (somewhat) implies that they are part of your project, and that you are distributing their codes. This conflicts your MIT license.

**Comment by gerdm** [comment]
Hi @zgbkdlm!

We are currently looking for implementations of the Unscented Rauch–Tung–Striebel smoother and the Statistically linearized Rauch–Tung–Striebel. See #29, #28, and #27 for details. Feel free to PR if you have implemented any of those.

As to the difference between JSL and ssm-jax, I'll let @murphyk comment on that.

**Comment by murphyk** [comment]
Hi @zgbkdlm . We are currently building up ssm-jax as a new repo which will eventually replace JSL. Both are open source
projects so we would love your contributions, since you are obviously an expert. However, since the ssm-jax API is still in flux, it may be best to make a PR in the JSL repo for now, until the dust settles. (PS. I have removed Sarkka's matlab code, due to incompatible GPL license.)
